### ISSUE TITLE
Form button text disappears

### ISSUE THREAD

**Issue by lampi87** [zucchi/ZucchiBootstrap#2]
I have one form with a collection
In this collection there are 2 buttons, one submit and one reset

If i try to send a form and it is not valid, then the reset button has no value and this leads to a blank and very small button
![button](https://f.cloud.github.com/assets/3034138/192070/e09df1b2-7f56-11e2-94a9-1c5d69f7dc1e.png)

**Comment by phpboyscout** [comment]
HI Alampr,

This is because the reset button is being treated as an input an on post php recieves a null value. Then when you set the data on your for for validation it sets the value for reset as null. The way around this is to use the Zucchi\Form\Element\Reset class:

```
$actions->add(array(
        'name' => 'reset',
        'type' => 'Zucchi\Form\Element\Reset',
        'attributes' => array(
            'class' => 'btn',
        ),
        'options' => array(
            'bootstrap' => array(
                'style' => 'inline',
            ),
        ),
    ));
```
